site_name: Shasta Wiki
site_description: 'A fundamental free energy market embedded into code.'
site_author: 'Shasta'
site_url: 'https://shasta.world/'

repo_name: 'shasta/shasta-wiki'
repo_url: 'https://github.com/Shasta/shasta-wiki'
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'
  logo: 'images/logo.png'
  feature:
    tabs: true
  font:
    text: 'Overpass'
    code: 'Overpass Mono'
pages:
  - Home: 'index.md'
  - Jobs:
      - Full-stack Developer: 'jobs/full.md'
  - FAQ: 'FAQ.md'
  - Design: 'design.md'
  - Blog posts: 'blog.md'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/shasta'
    - type: 'twitter'
      link: 'https://twitter.com/ethshasta'
    - type: 'linkedin'
      link: 'https://linkedin.com/company/shastaproject'
